CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pathfinder_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO pathfinder_user;
